### ISSUE TITLE
moving to ols 2

### ISSUE THREAD

**Issue by ypriverol** [hbarsnes/ols-dialog#1]
@hbarsnes we need to move our tools to the new version of ols http://www.ebi.ac.uk/ols/beta/ we should try to schedule this movement and the tasks. Let me know what do you think. The current version of ols web-services will be discontinued in 6 months.

**Comment by ypriverol** [comment]
@hbarsnes we don't even need to do changes in the ols-dialog, the dependency that we should change is the ols-client. Do you have the code of this library? Perhaps Richard Cotte?

**Comment by hbarsnes** [comment]
@ypriverol I'm afraid I never had access to the ols-client code, only used it as a dependency in the OLS Dialog. And yes, asking Richard is perhaps the best choice, but I would have thought that you had access to the code at the EBI? Not sure if the source code was on Google Code or not?

Regarding the use of the OLS Dialog, we don't really use it anymore after moving from PRIDE XML to mzIdentML export in PeptideShaker. So the easier it will be to update to the new OLS the better. You really sure it will be as easy replacing the dependency..?

**Comment by ypriverol** [comment]
@hbarsnes harald we would need to compile for sure but I would guess that if we keep the same datastructures and the functions for ols-dialog it should work. In any case if you are not using ols-dialog probably the best option is to do a refactoring on it as well.

**Comment by hbarsnes** [comment]
@ypriverol We only used the OLS Dialog in the deprecated PRIDE Converter 1.0 and in the outdated PRIDE XML export in PeptideShaker, so feel free to refactor the code if you think that this would be an advantage.

**Comment by ypriverol** [comment]
OK

**Comment by nielshulstaert** [comment]
Dear Yasset,

I use the ols dialog in another project we are working on, so it would 
be really great if you could update it to the new ols version. I'm also 
using the maven cxf plugin to generate java code to access to ols soap 
service directly so I'll have to look for an alternative approach (I 
guess the cxf-wadl2java-plugin does the same thing as the 
cxf-wsdl2java-plugin).

Let me know if I can do anything and thinks for reminding me of this.

Best regards,

Niels

On 02/03/2016 01:06 PM, Yasset Perez-Riverol wrote:

> OK
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/compomics/ols-dialog/issues/1#issuecomment-179188969.

## 

Niels Hulstaert, Software developer

Computational Omics and Systems Biology Group
Department of Medical Protein Research
Universiteit Gent - VIB

A. Baertsoenkaai 3
B9000 Gent
Belgium

Tel: +32-92649365
Fax: +32-92649484

Skype: nielshulstaert

**Comment by ypriverol** [comment]
Ok, I will let you know what is our final decision here and our roadmap plan for the migration.
